FROM python:3.11-slim

WORKDIR /app

# Copy requirements and model from parent context
# RUN cd ..
COPY money_monitoring/requirements.txt .
COPY model/ ./model/
RUN pip install --no-cache-dir -r requirements.txt

COPY money_monitoring/main.py .

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
